### ISSUE TITLE
Addon only works in English WoW client

### ISSUE THREAD

**Issue by cremor** [zodiakbg/CharacterPanelUpgradeTrack#1]
After installing the addon nothing was visible in the character panel. Also no error was thrown.

I checked the code and found that it only works for english WoW clients because of hardcoded strings:
https://github.com/zodiakbg/CharacterPanelUpgradeTrack/blob/478ddc4082e35f2e4cacbce25edcb5f8647fc0a0/libs/tooltip.lua#L5-L14

PS: Placing your code files in a folder named "libs" is confusing. The usual convention is that the "libs" folder is used for third party libraries that the addon relies on.

**Comment by alexanderstoev** [comment]
Thanks for the feedback. I agree on both points.

I added a note in the description of the addon on Curse that it works only on the English client. 

And on the "libs" folder name - semantics :) 
"utils" might be better name for the purpose it serves.

As of now I don't plan to fix this soon - hopefully by the end of the year.

**Comment by alexanderstoev** [comment]
@cremor,
Just pushed a new version with better localization support (some locales are still not supported).
And renamed the libs to utils as suggested.

Thanks for the feedback
